### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by fanyang2016** [grandcentrix/tray#121] opened 2017-11-01 07:43 UTC
[//]: # (We want to provide the best support with your issue. So please answer the following questions carefully)
[//]: # (You don't have an issue but a remark or a feature? Please remove this default template and just write your text 😉)

#### Stacktrace
<details>
  <summary>Stacktrace</summary>
          minSdkVersion 14 is OK?
</details>

**Comment by StefMa** [comment] 2017-11-01 13:46
Duplicate of #122

**Closed by StefMa** 2017-11-01 13:46 UTC
